# class_name Global
extends Node

enum GATE_TYPE {
	START_GATE,
	ARROW_GATE,
	SPLIT_GATE,
	TELEPORT_GATE,
	FLAG_GATE,
	BOUNCY_GATE,
	EMPTY_GATE,
	GROUND_GATE,
	BELT_GATE,
	TURN_GATE,
}

var GATE_TO_NAME = {
	GATE_TYPE.START_GATE: 'Start Gate',
	GATE_TYPE.ARROW_GATE: 'Arrow Gate',
	GATE_TYPE.SPLIT_GATE: 'Split Gate',
	GATE_TYPE.TELEPORT_GATE: 'Portal Gate',
	GATE_TYPE.FLAG_GATE: 'Flag',
	GATE_TYPE.BOUNCY_GATE: 'Bouncy Gate',
	GATE_TYPE.EMPTY_GATE: 'Empty Gate',
	GATE_TYPE.GROUND_GATE: 'Ground Gate',
	GATE_TYPE.BELT_GATE: 'Belt Gate',
	GATE_TYPE.TURN_GATE: 'Turn Gate',
}

var GATE_ATLAS_SEPARATION = 2
var GATE_ATLAS_X_OFFSET = 120
var GATE_ATLAS_Y_OFFSET = 140
var GATE_TO_ATLAS = {
	GATE_TYPE.START_GATE: Vector2(1, 0),
	GATE_TYPE.ARROW_GATE: Vector2(0, 0),
	GATE_TYPE.SPLIT_GATE: Vector2(3, 0),
	GATE_TYPE.TELEPORT_GATE: Vector2(2, 0),
	GATE_TYPE.FLAG_GATE: Vector2(0, 1),
	GATE_TYPE.BOUNCY_GATE: Vector2(1, 1),
	GATE_TYPE.EMPTY_GATE: Vector2(0, 8),
	GATE_TYPE.GROUND_GATE: Vector2(0, 8),
	GATE_TYPE.BELT_GATE: Vector2(2, 1),
	GATE_TYPE.TURN_GATE: Vector2(3, 1),
}
